projects:
  src:
    schemaPath: src/graphql/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:3002/graphql
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/prisma.ts
