version: '3.3'
services:
  entities-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=entities
      - POSTGRES_DATABASE=entities
      - POSTGRES_PASSWORD=mypass
    ports:
      - "5432:5432"
  prisma:
    image: prismagraphql/prisma:1.10
    restart: always
    ports:
      - "4466:4466"
    depends_on:
      - entities-db
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            active: true
            host: entities-db
            port: 5432
            user: entities
            password: mypass
  entities-service:
    image: app
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     NPM_TOKEN: ${NPM_TOKEN}
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      
    ports:
      - "3002:3002"
    depends_on:
      - prisma
    entrypoint: "yarn test:flow:ci"