version: '3.5'
services:
  entities-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=entities
      - POSTGRES_DATABASE=entities
      - POSTGRES_PASSWORD=mypass
    ports:
      - "5432:5432"
    networks:
      - envisioning
  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - envisioning
  prisma:
    image: prismagraphql/prisma:1.10
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            active: true
            host: entities-db
            port: 5432
            user: entities
            password: mypass
    networks:
      - envisioning
  # entities:
  #   depends_on:
  #     - rabbit
  #     - prisma
  #     - redis
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       NPM_TOKEN: ${NPM_TOKEN}
  #   ports:
  #     - "3002:3002"
  #   environment:
  #     - NODE_ENV=dev
  #     - POSTGRES_URI=postgres://auth:mypass@entities-db:5432/auth
  #     - RABBITMQ_URI=amqp://rabbit:5672
  #     - PRISMA_ENDPOINT=http://prisma:4466
  #     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #   networks:
  #     - envisioning
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment: 
      - REDIS_PASSWORD=redispassword
    networks:
      - envisioning
networks:
  envisioning:
    name: envisioning