version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  check-typescript:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Build typescript
          command: yarn check-typescript

  check-version:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Checks if version already exists
          command: |
            export NPM_PACKAGE_VERSION=$(node -pe "require('./package.json').version")
            ! docker pull formicarium/tanajura:$NPM_PACKAGE_VERSION

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Test
          command: yarn test

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Test
          command: yarn test

  build-docker:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: Build Docker image
          command: docker build --cache-from=app -t app .
      - deploy:
          name: Push Docker image
          command: |
            export NPM_PACKAGE_VERSION=$(node -pe "require('./package.json').version")
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker tag app formicarium/tanajura:${NPM_PACKAGE_VERSION}
            docker push formicarium/tanajura:${NPM_PACKAGE_VERSION}



workflows:
  version: 2
  build-test-release:
    jobs:
      - install-dependencies
      - check-typescript:
          requires:
            - install-dependencies
      - check-version
      - test:
          requires:
            - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - build-docker:
          filters:
            branches:
              only:
                - master
          requires:
            - check-typescript
            - test
            - lint
