version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: rhinogram/node-awscli

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command:
            yarn install
      - run:
          name: Typescript
          command: yarn check-typescript
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - run:
          name: Semantic release
          command: |
            yarn semantic-release
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - deploy:
          name: Push application Docker image
          command: |
            export NPM_PACKAGE_VERSION=$(node -pe "require('./package.json').version")
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker tag app formicarium/tanajura:${NPM_PACKAGE_VERSION}
            docker push formicarium/tanajura:${NPM_PACKAGE_VERSION}
workflows:
  version: 2
  build-test-release:
    jobs:
      - build-test-publish